crud/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::resource('crud', 'CrudController');

Route::resource('api', 'apiController');

crud/app/Jobs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jobs extends Model
{
    protected $fillable = [
        'jobname',
        'jobdesc',
        'joblocation'
    ];
    public $timestamps = false;
    protected $table = 'jobs';
    Protected $primaryKey = "ID";
}

crud/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

crud/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

crud/app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\jobs;
use App\Http\Requests;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = jobs::all();
        $name = 'display';

        return view('pages.index')
            ->with('jobs', $jobs)
            ->with('name', $name);
        }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $job = new jobs;
        $job->jobname = $request->name;
        $job->jobdesc = $request->description;
        $job->joblocation = $request->location;
        $job->save();

        return redirect()->route('crud.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $job = jobs::find($id);
        $name = 'read';
        return view('pages.read')
            ->with('job', $job)
            ->with('name', $name);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $job = jobs::find($id);
        $name = 'update';
        return view('pages.update')
            ->with('job', $job)
            ->with('name', $name);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $job = jobs::find($id);

        $job->jobname = $request->name;
        $job->jobdesc = $request->description;
        $job->joblocation = $request->location;
        $job->save();

        return redirect()->route('crud.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $job =  jobs::where('ID', $id)->delete();
        return redirect()->route('crud.index');
    }
}

crud/app/Http/Controllers/apiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\jobs;
use App\Http\Requests;

class apiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jobs = jobs::all();
        return($jobs);
    }



    public function show($id)
    {
        $job = jobs::find($id);

        return($job);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */



}

crud/app/Http/Controllers/pagesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

class pagesController extends Controller
{
    public function getCreate(){

        $name = 'create';
        return view("pages.create")->with("name", $name);

    }

    public function getRead(){
        $name = 'read';
        return view("pages.read")
            ->with("name", $name);
    }

    public function getUpdate(){
        $name = 'update';
        return view("pages.update")
            ->with("name", $name);
    }

    public function getDelete(){
        $name = 'delete';
        return view("pages.delete")
            ->with("name", $name);
    }
}

crud/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>@yield('title')</title>

    {!! HTML::style('css/bootstrap.min.css') !!}
    {!! HTML::style('css/style.css') !!}
</head>
<body>
    @include('layouts.menu')
    <section class="main">
    @yield('body')
    </section>
    {!! HTML::script('js/jquery-1.12.4.js') !!}
    {!! HTML::script('js/bootstrap.min.js') !!}
</body>
</html>

crud/resources/views/layouts/menu.blade.php
<header class="jumbotron">
    <h1>crud app created by Michiel Vanhaverbeke</h1>
</header>

crud/resources/views/pages/create.blade.php
@extends('layouts.layout')
    @section('title')
        create
    @stop

    @section('body')
        <section class="title">
            <h2>create a new record</h2>
        </section>

        <div id="form">

        {!!Form::open(['route' => 'crud.store'])!!}

        {!! Form::label('name', 'name') !!}
        {!! Form::text('name', null,['placeholder' => 'name', 'class' => 'form-control']) !!}<br>

        {!! Form::label('description', 'description') !!}
        {!! Form::text('description', null,['placeholder' => 'desc', 'class' => 'form-control']) !!}<br>

        {!! Form::label('location', 'location') !!}
        {!! Form::text('location', null,['placeholder' => 'location', 'class' => 'form-control']) !!}<br>

        {!! Form::submit('create',['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
        </div>
    @stop

crud/resources/views/pages/delete.blade.php
@extends('layouts.layout')
@section('title')
    {{$name}}
@stop

@section('body')
    <h1>this is the {{$name}} page</h1>
    <p>{{$name}}</p>
@stop

crud/resources/views/pages/index.blade.php
@extends('layouts.layout')
@section('title')
    {{$name}}

@stop


@section('body')
    <section class="title">
    <h2>this is the {{$name}} page</h2>
    </section>

    <table class="table">
        <tr>
            <th>id</th>
            <th>jobname</th>
            <th>jobdescription</th>
            <th>joblocation</th>
            <th></th>
        </tr>
    @foreach ($jobs as $job)
        <tr>
            <td>{{$job->ID}}</td>
        <td>{{ $job->jobname }}</td>
        <td>{{ $job->jobdesc }}</td>
            <td>{{ $job->joblocation }}</td>
        <td><a href="{{route('crud.show', $job->ID)}}" class="btn btn-primary">select</a></td>
        </tr>
    @endforeach
    </table>
    <a href="{{route('crud.create')}}" class="btn btn-success">new entry</a>
@stop

crud/resources/views/pages/read.blade.php
@extends('layouts.layout')
@section('title')
    {{$name}}
@stop

@section('body')

    <section class="title">
    <h2>you have selected the item with id: {{$job->ID}}</h2>
    </section>

    {!!Form::open([
    'method'=> 'delete',
    'route' => ['crud.destroy', $job->ID]])!!}
    <table class="table">
        <tr>
            <th>id</th>
            <th>jobname</th>
            <th>jobdescription</th>
            <th>joblocation</th>

        </tr>
        <tr>
        <td>{{$job->ID}}</td>
        <td>{{ $job->jobname }}</td>
        <td>{{ $job->jobdesc }}</td>
        <td>{{ $job->joblocation }}</td>
        </tr>
    </table>





    <a href="{{route('crud.edit', $job->ID)}}" class="btn btn-primary">edit</a>
    {!! Form::submit('delete', ['class'=>'btn btn-danger'])!!}
    {!! Form::close()!!}
@stop

crud/resources/views/pages/update.blade.php
@extends('layouts.layout')
@section('title')
    {{$name}}
@stop

@section('body')


    <section class="title">
    <h2>you have chosen to edit record with id: {{$job->ID}}</h2>
    </section>
    <div id="form">
    {!!Form::model($job,[
    'method' => 'patch',
    'route' => ['crud.update', $job->ID]])!!}

    {!! Form::label('name', 'name') !!}
    {!! Form::text('name', $job->jobname,['placeholder' => 'name', 'class' => 'form-control']) !!}<br>

    {!! Form::label('description', 'description') !!}
    {!! Form::text('description', $job->jobdesc,['placeholder' => 'desc', 'class' => 'form-control']) !!}<br>

    {!! Form::label('location', 'location') !!}
    {!! Form::text('location', $job->joblocation ,['placeholder' => 'location', 'class' => 'form-control']) !!}<br>

    {!! Form::submit('save', ['class'=>'btn btn-primary'])!!}
    {!! Form::close()!!}
    </div>
@stop